CREATE TABLE default_words (
  id bigint generated by default as identity primary key,
  Words varchar(255)
);

CREATE TABLE players_words (
  id bigint generated by default as identity primary key,
  Created_time timestamp with time zone default timezone('utc'::text, now()) not null,
  Words varchar(255),
  Right_letter varchar(255),
  Wrong_letter varchar(255)
);

